# 开发环境配置
feishu:
  base_url: "https://open.feishu.cn"
  tenant_access_token: "t-g10475jtDD46FY64TKRIUEUFPVLVAXRM7XTOM6P5"
  app_id: "your_app_id"
  app_secret: "your_app_secret"
  token_expire: 5400  # token过期时间(秒)

# 测试账号
test_accounts:
  - name: "张麻子"
    open_id: "ou_d43b3eacf22b2f76b8672e6d95e14641"
    chat_id: "your_chat_id"
#    email: "testuser@example.com"

#  - name: "测试群组A"
#    chat_id: "oc_xxxxx"

# API特定配置
apis:
  message:
    rate_limit: 5    # QPS限制
    max_length: 150   # 最大长度(KB)
    allowed_types:    # 允许的消息类型
      - "text"
      - "post"
      - "image"
      - "interactive"